SELECT curdate();

SELECT LOCALTIMESTAMP();

SELECT CURRENT_TIMESTAMP();

SELECT YEAR(current_timestamp());

SELECT MONTH(current_timestamp());

SELECT DAY(current_timestamp());

SELECT MONTHNAME(CURRENT_TIMESTAMP());

SELECT DAYNAME(CURRENT_TIMESTAMP());

SELECT DATEDIFF(CURRENT_TIMESTAMP(), "2021-01-01") AS DIFERENCIAS_DE_DIAS;

SELECT DATEDIFF(CURRENT_TIMESTAMP(), "1994-10-29") AS DIFERENCIAS_DE_DIAS;

SELECT DATEDIFF(CURRENT_TIMESTAMP(), "2020-02-20") AS DIFERENCIAS_DE_DIAS;

SELECT CURRENT_TIMESTAMP() AS DIA_HOY, DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 1 MONTH) AS RESULT;

SELECT DISTINCT FECHA_VENTA,
DAYNAME(FECHA_VENTA) AS DIA, MONTHNAME(FECHA_VENTA) AS MES,
YEAR(FECHA_VENTA) AS AÑO FROM facturas;


SELECT NOMBRE, TIMESTAMPDIFF(YEAR, FECHA_DE_NACIMIENTO, CURDATE()) AS    EDAD
FROM  tabla_de_clientes;


