USE ventas_jugos;

ALTER TABLE tb_items_facturas ADD CONSTRAINT FK_FACTURA FOREIGN KEY (NUMERO) REFERENCES tb_factura;

ALTER TABLE tb_items_facturas ADD CONSTRAINT FK_PRODUCTO
FOREIGN KEY (CODIGO) REFERENCES tb_producto(CODIGO);