CREATE TABLE `tb_producto2` (
  CODIGO VARCHAR(10) NOT NULL,
  DESCRIPCION VARCHAR(100) DEFAULT NULL,
  SABOR VARCHAR(50) DEFAULT NULL,
  TAMANO VARCHAR(50) DEFAULT NULL,
  ENVASE VARCHAR(50) DEFAULT NULL,
  PRECIO_LISTA FLOAT DEFAULT NULL,
  PRIMARY KEY (CODIGO)
);