CREATE TABLE tb_facturacion(
  FECHA DATE NULL,
  VENTA_TOTAL FLOAT
);

SELECT * FROM tb_facturacion;

-- table faturas

CREATE TABLE tb_factura1 (
  NUMERO VARCHAR(5) NOT NULL,
  FECHA DATE DEFAULT NULL,
  DNI VARCHAR(11) NOT NULL,
  MATRICULA VARCHAR(5) NOT NULL,
  IMPUESTO FLOAT DEFAULT NULL,
  PRIMARY KEY (NUMERO),
  KEY FK_CLIENTE1 (DNI),
  KEY FK_VENDEDOR1 (MATRICULA),
  CONSTRAINT FK_CLIENTE1 FOREIGN KEY (DNI) REFERENCES tb_cliente (NUMERO)
  CONSTRAINT FK_VENDEDOR FOREIGN KEY (MATRICULA) REFERENCES tb_vendedor (CODIGO)
);

-- vendedor 
CREATE TABLE tb_items_facturas1 (
  NUMERO VARCHAR(5) NOT NULL,
  CODIGO VARCHAR(10) NOT NULL,
  CANTIDAD INT DEFAULT NULL,
  PRECIO FLOAT DEFAULT NULL,
  PRIMARY KEY (NUMERO, CODIGO),
  KEY FK_PRODUCTO1 (CODIGO),
  CONSTRAINT FK_FACTURA1 FOREIGN KEY (NUMERO) REFERENCES tb_factura1(NUMERO)
  CONSTRAINT FK_PRODUCTO1 FOREIGN KEY (CODIGO) REFERENCES tb_producto(CODIGO)
);


SELECT * FROM tb_items_facturas1;
select * from tb_facturaa;

INSERT INTO tb_factura1
VALUES('0100', '2021-01-01', '1234234231', '243', 0.10)


-- inner

INSERT INTO tb_facturacion
SELECT A.FECHA, SUM(B.CANTIDAD * B.PRECIO) AS VENTA_TOTAL
FROM tb_factura1 A
INNER JOIN
tb_items_facturas1 B
ON A.NUMERO = B.NUMERO
GROUP BY A.FECHA;

-- TRIGGER
DELETE FROM tb_facturacion;

DELIMITER //

CREATE TRIGGER TG_FACTURACION_INSERT
AFTER INSERT ON tb_items_facturas1
FOR EACH ROW BEGIN

  DELETE FROM tb_facturacion;
  INSERT INTO tb_facturacion
  SELECT A.FECHA, SUM(B.CANTIDAD * B.PRECIO) AS VENTA_TOTAL
  FROM tb_factura1 A
  INNER JOIN
  tb_items_facturas1 B
  ON A.NUMERO = B.NUMERO
  GROUP BY A.FECHA;


END //


INSERT INTO tb_factura1
VALUES('0100', '2021-01-01', '1234234231', '243', 0.10)

INSERT INTO tb_items_factura1
VALUES ('1010101', '1423423', 100, 25),
  ('1010102', '14234223', 200, 35);
;


-- inner

INSERT INTO tb_facturacion
SELECT A.FECHA, SUM(B.CANTIDAD * B.PRECIO) AS VENTA_TOTAL
FROM tb_factura1 A
INNER JOIN
tb_items_facturas1 B
ON A.NUMERO = B.NUMERO
GROUP BY A.FECHA;

-- TRIGGER
DELETE FROM tb_facturacion;

DELIMITER //

CREATE TRIGGER TG_FACTURACION_INSERT
AFTER INSERT ON tb_items_facturas1
FOR EACH ROW BEGIN

  DELETE FROM tb_facturacion;
  INSERT INTO tb_facturacion
  SELECT A.FECHA, SUM(B.CANTIDAD * B.PRECIO) AS VENTA_TOTAL
  FROM tb_factura1 A
  INNER JOIN
  tb_items_facturas1 B
  ON A.NUMERO = B.NUMERO
  GROUP BY A.FECHA;


END //


INSERT INTO tb_factura1

VALUES('0100', '2021-01-01', '1234234231', '243', 0.10)

-- Edad del cliente
SELECT DNI, EDAD, FECHA_NACIMIENTO, timestampdiff(YEAR, FECHA_NACIMIENTO, NOW()) AS ANOS FROM tb_clientes;

DELIMITER //
CREATE TRIGGER TG_EDAD_CLIENTES_INSERT 
BEFORE INSERT ON tb_clientes
FOR EACH ROW BEGIN
SET NEW.EDAD = timestampdiff(YEAR, NEW.FECHA_NACIMIENTO, NOW());
END//
