CREATE TABLE tb_cliente(
  DNI VARCHAR(11) NOT NULL,
  NOMBRE VARCHAR(100) DEFAULT NULL,
  DIRECCION VARCHAR(150) DEFAULT NULL,
  BARRIO VARCHAR(50) DEFAULT NULL,
  CIUDAD VARCHAR(50) DEFAULT NULL,
  ESTADO VARCHAR(45) DEFAULT NULL,
  CP VARCHAR(8) DEFAULT NULL,
  FECHA_NACIMIENTO date DEFAULT NULL,
  EDAD INT(2) DEFAULT NULL,
  SEXO VARCHAR(1) DEFAULT NULL,
  LIMITE_CREDITO float DEFAULT NULL,
  VOLUMEN_COMPRA float DEFAULT NULL,
  PRIMERA_COMPRA bit(1) DEFAULT NULL,
  PRIMARY KEY(DNI));
ENGINE = InnoDB;