CREATE TABLE `ventas_jugos`.`facturas` (
  `NUMERO` VARCHAR(5) NOT NULL,
  `FECHA` DATE NULL,
  `DNI` VARCHAR(11) NOT NULL,
  `MATRICULA` VARCHAR(5) NULL,
  `IMPUESTO` FLOAT NULL,
  PRIMARY KEY (`NUMERO`))
ENGINE = InnoDB;
