CREATE TABLE tb_producto(
  CODIGO VARCHAR(10) NOT NULL,
  DESCRIPCION VARCHAR(100) NULL,
  SABOR VARCHAR(50) NULL,
  TAMANO VARCHAR(50) NULL,
  ENVASE VARCHAR(50) NULL,
  PRECIO_LISTA FLOAT NULL,
  PRIMARY KEY(CODIGO)
);