CREATE TABLE `empresa`.`vendedores` (
  `MATRICULA` VARCHAR(5) NOT NULL,
  `NOMBRE` VARCHAR(100) NULL,
  `BARRIO` VARCHAR(50) NULL,
  `COMISION` FLOAT NULL,
  `FECHA_ADMISION` DATE NULL,
  `VACACIONES` BIT(1) NULL,
  PRIMARY KEY (`MATRICULA`));

  