CREATE TABLE facturas(
  NUMERO VARCHAR(5) NOT NULL,
  FECHA DATE,
  DNI VARCHAR(11) NOT NULL,
  MATRICULA VARCHAR(5) NOT NULL,
  IMPUESTO FLOAT,
  PRIMARY KEY (NUMERO),
  FOREIGN KEY (DNI) REFERENCES clientes(DNI),
  FOREIGN KEY (MATRICULA) REFERENCES vendedores(MATRICULA)
);