CREATE TABLE items(
  NUMERO VARCHAR(5) NOT NULL,
  CODIGO VARCHAR(10) NOT NULL,
  CANTIDAD INT,
  PRECIO FLOAT,
  PRIMARY KEY (NUMERO, CODIGO),
  FOREIGN KEY (NUMERO) REFERENCES facturas(NUMERO),
  FOREIGN KEY (CODIGO) REFERENCES productos(CODIGO)
);